version: "3"
services:
   api-server:
      image: api-server
      ports:
       - "5000:5000"
      build: 
        context: ./server
        dockerfile: Dockerfile
      networks:
       - mern-app
      environment:
        CHOKIDAR_USEPOLLING: "true"
      volumes:
       - ./server:/usr/server
   react-app:
      image: react-app
      stdin_open: true
      ports: 
         - "3000:3000"
      build: 
         context: ./client
         dockerfile: Dockerfile
      networks:
         - mern-app
      depends_on: 
         - api-server
      volumes:
         - ./client:/usr/client
networks:
  mern-app:
    driver: bridge